# Site settings
title: Bizouarn
email: aymeric@bizouarn.fr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://git.bizouarn.com" # the base hostname & protocol for your site
github_username:  bizouarn
twitter_username: aymericbizouarn

# Build settings
markdown: kramdown