# Site settings
title: Bizouarn
email: aymeric@bizouarn.fr
baseurl: ""
url: "http://git.bizouarn.com"
github_username:  bizouarn
twitter_username: aymericbizouarn
gitlab_username: bizouarn
footer_msg: Vous avez le même patronyme que moi, n'hésitez pas à me contacter si vous voulez une redirection en .bizouarn.fr ou .bizouarn.com.

# Build settings
markdown: kramdown